server:
  port: 80

spring:
  application:
    name: cloud-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  zipkin:
    #监控地查看址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率
      probability: 1

feign:
  client:
    config:
      #指定全局
      default:
        #连接超时时间
        connectTimeout: 5000
        #服务等待时间
        readTimeout: 5000
        loggerLevel: full
