server:
  port: 8001

spring:
  application:
    name: cloud-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  zipkin:
    #监控地查看址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率
      probability: 1
